# Generated by Django 4.1.4 on 2023-02-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('Tel', models.IntegerField()),
                ('DOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('Tel', models.PositiveIntegerField()),
                ('Salary', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Img', models.ImageField(upload_to='')),
                ('Des', models.TextField()),
                ('Ingredients', models.TextField()),
                ('Promotion', models.IntegerField()),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cu_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturantapp.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ResturantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ResturantSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturantapp.resturanttable')),
                ('seatsNum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturantapp.reservationrecord')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('TableNum', models.IntegerField()),
                ('Order_time', models.DateField()),
                ('E_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturantapp.employee')),
                ('MenuID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturantapp.menurecord')),
            ],
        ),
    ]
